import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Braah_One,
  Poppins,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import ThemeProvider from "./component/Themeprovider";
import { ScrollProvider } from "./utils/scrollContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BraahOne = Braah_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-braa",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
const mont = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${BraahOne.variable} ${mont.variable} ${poppins.variable}`}>
        <ThemeProvider>
          <ScrollProvider>
            {children}
          </ScrollProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
